package com.thirdpartpay.web.model;

public class CustomerAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_account.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_account.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_account.account_id
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_account.id
     *
     * @return the value of customer_account.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_account.id
     *
     * @param id the value for customer_account.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_account.customer_id
     *
     * @return the value of customer_account.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_account.customer_id
     *
     * @param customerId the value for customer_account.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_account.account_id
     *
     * @return the value of customer_account.account_id
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_account.account_id
     *
     * @param accountId the value for customer_account.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
}