package com.thirdpartpay.common.model;

import java.io.Serializable;
import java.util.Date;

public class BusinessRecoder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_recoder.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_recoder.first_part
     *
     * @mbggenerated
     */
    private Integer firstPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_recoder.second_part
     *
     * @mbggenerated
     */
    private Integer secondPart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_recoder.money
     *
     * @mbggenerated
     */
    private Long money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_recoder.start_time
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_recoder.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_recoder.flag
     *
     * @mbggenerated
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_recoder.business_id
     *
     * @return the value of business_recoder.business_id
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_recoder.business_id
     *
     * @param businessId the value for business_recoder.business_id
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_recoder.first_part
     *
     * @return the value of business_recoder.first_part
     * @mbggenerated
     */
    public Integer getFirstPart() {
        return firstPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_recoder.first_part
     *
     * @param firstPart the value for business_recoder.first_part
     * @mbggenerated
     */
    public void setFirstPart(Integer firstPart) {
        this.firstPart = firstPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_recoder.second_part
     *
     * @return the value of business_recoder.second_part
     * @mbggenerated
     */
    public Integer getSecondPart() {
        return secondPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_recoder.second_part
     *
     * @param secondPart the value for business_recoder.second_part
     * @mbggenerated
     */
    public void setSecondPart(Integer secondPart) {
        this.secondPart = secondPart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_recoder.money
     *
     * @return the value of business_recoder.money
     * @mbggenerated
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_recoder.money
     *
     * @param money the value for business_recoder.money
     * @mbggenerated
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_recoder.start_time
     *
     * @return the value of business_recoder.start_time
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_recoder.start_time
     *
     * @param startTime the value for business_recoder.start_time
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_recoder.end_time
     *
     * @return the value of business_recoder.end_time
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_recoder.end_time
     *
     * @param endTime the value for business_recoder.end_time
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_recoder.flag
     *
     * @return the value of business_recoder.flag
     * @mbggenerated
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_recoder.flag
     *
     * @param flag the value for business_recoder.flag
     * @mbggenerated
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}