package com.thirdpartpay.web.mapper;

import com.thirdpartpay.web.model.CustomerAccount;
import com.thirdpartpay.web.model.CustomerAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int countByExample(CustomerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int insert(CustomerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int insertSelective(CustomerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    List<CustomerAccount> selectByExample(CustomerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    CustomerAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerAccount record, @Param("example") CustomerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerAccount record, @Param("example") CustomerAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerAccount record);
}